### ISSUE TITLE
Fix routes on 2016, move passenger to /elections/2016 rather than /elections

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2017#54]
So we can deploy 2017 to /elections/2017

**Comment by kowall116** [comment]
John was able to move to the new folder seemingly pretty smoothly. The only error I'm seeing in the browser console is:

```javascript
{
  "name": "Error",
  "message": "Not Found",
  "stack": "Error: Not Found\n    at http://elections.dev.passenger.bostonglobe.com/elections/static/bundle.js?_=0.0.9:33:15176\n    at <anonymous>"
}
```
This might relate to the issue we're having with 2017 bundle.js however the js on the page seems to be working.

**Comment by gopperman** [comment]
Once you get past that, I definitely think you are going to have to update
the routes and urlmanager. Nice progress so far.
